
platform :osx, '10.7'
source 'https://github.com/CocoaPods/Specs.git'

target 'NBULogDemo' do
    # For regular projects
    #pod 'NBULog'

    # For development
    pod 'NBULog', :path => '../../'
end
