
platform :ios, '5.0'
source 'https://github.com/CocoaPods/Specs.git'

# For regular projects
#pod 'NBULog'

# Optional for on-device log console
pod 'LumberjackConsole'

# For development
pod 'NBULog', :path => '../../'

