
platform :ios, '8.0'
use_frameworks!

target 'NBULogDemo' do
    
    # For regular projects
    #pod 'NBULog'

    # Optional for on-device log console
    #pod 'NBULog/Console'

    # For development
    pod 'NBULog/Console', :path => '../../'

end
